# -*- coding: utf-8 -*-
"""Lecture5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UmcAQ99i4Nw71hWltiyCY6diBiDl0kGF
"""

#Maseeng Masitha
#28 January 2020
#Python 3.4
#Lecture 5

# Commented out IPython magic to ensure Python compatibility.
#Modulus Operator
# % deivides two numbers and returns the remainder
quotient = 7/3
print(quotient)

remainder = 7% 3 #modulus operator
print(remainder)

#Boolean Expressions
6%3==0 #What's the output?

7%3==0 #What's the output?

#Above= lead to logical expressions

x== area > 154 and suitability > 0.9

#Negating an expression
not (5>10)

#Conditional execution
#The following is an "if" statement
water_per_person = 20 # in litres per day according to SPHERE standards.
if water_per_person>19:
  print("water_per_person, :post emergency levels.")

x = 16
if x %2 ==0:
  print("x is even.")
else:
  print("x is odd.")

#Exercise 1
#Defining a function
def tide (m):
  if m %2 == 1:
    print ("tide is high.")
  else:
    print ("tide is low.")
tide(8)

def print_parity(n):
  if n % 2 == 0:
    print (n,"is an even number.")
  else:
      print (n, "is an odd number.")

# Comment code...
def ifequal(x,y):

#Nested conditionals
def ifequal(x,y):
  if x < y:
    print (x, "is less than", y) 
  elif x > y:
    print (x, "is greater than", y)
  else:
    print (x, "is equal to", y)
  
ifequal (9,10)