# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bwJdD7QEgppsgRyDd1HzZRKVw_F7Q6Xu
"""

Author: Maseeng 
Created: 20 Jan 2020
Time: 
# This is some sample code.
"""
message = "Python version 3.4"
n = 17
pi = 3.14159


print (message)
print (n)


print (pi)

# What happens when we run this?
print(type (message))
print (type (n))
print (type (pi))

folder = "d:/data/ma/"
file_1 = "roads.shp"
road_layer = folder + file_1
print (road_layer)

my_string = "pointdata"
print (my_string*3)

n =  42
print ("first line\n second line")

n =42
print ("first line\\second line")

n =  42
print ("first line\second line")

str = "Have you read "Things Fall Apart"?"
str = 'Have you read \"Things Fall Apart"?'
print (str)
"""

#These lines output the results
pi = 3.14
r = 2.0
area = pi * (r**2)
perim = 2.0 * pi * r
print "Given r: ", r
print "Area is: ", area
print  "perimeter is: ", perim